apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phasor-kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: services
  source:
    repoURL: file:///gitops
    targetRevision: HEAD
    path: manifests/phasor-kargo/management-eu-central-1
  destination:
    server: https://kubernetes.default.svc
    namespace: phasor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
