apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eu-central-1-management
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana-operator
      targetRevision: v5.20.0
      helm:
        valueFiles:
          - $values/manifests/grafana-operator/eu-central-1-management/values.yaml
    - repoURL: file:///gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-extension
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "71"
spec:
  project: eu-central-1-management
  source:
    repoURL: file:///gitops
    targetRevision: HEAD
    path: manifests/grafana-extension/eu-central-1-management
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
