apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eu-central-1-prod-namespaces
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: eu-central-1-prod
  source:
    repoURL: file:///gitops
    targetRevision: HEAD
    path: manifests/namespaces/eu-central-1-prod
  destination:
    name: eu-central-1-prod-eu-central-1
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
