apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-mixin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "820"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  project: platform
  sources:
    - repoURL: ghcr.io/monkescience/helm-charts
      chart: gitops-mixin
      targetRevision: 0.11.0
      helm:
        valueFiles:
          - $values/manifests/gitops-mixin/dev-eu-central-1/values.yaml
    - repoURL: file:///gitops
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
