apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-dev-eu-central-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: dev-eu-central-1
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      targetRevision: 3.13.0
      helm:
        valueFiles:
          - $values/manifests/metrics-server/dev-eu-central-1/values.yaml
    - repoURL: file:///gitops
      targetRevision: HEAD
      ref: values
  destination:
    name: dev-eu-central-1
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
