apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eu-central-1-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eu-central-1-management
  source:
    repoURL: file:///gitops
    targetRevision: HEAD
    path: apps/eu-central-1-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
