apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: file:///gitops
    targetRevision: HEAD
    path: apps/management-eu-central-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
